announcer:
  enabled: true
  interval: 30
  random-order: false
  prefix: "<#B00B1E>=== MP BEGIN ===\n<reset> "
  suffix: " \n<reset><#B00B1E>=== MP END ==="
  messages:
    - "<yellow>Hello, world!"
    - "<bold>The cake is a <#FF0000><bold>lie."
    - "<blue>Look Ma\n<red>Two lines!"