name: "Megaphone"
version: ${project.version}
description: "Automatically broadcast pre-defined messages after set periods of time."
author: "winnpixie"
website: "https://winnpixie.github.io/"
main: "io.github.winnpixie.megaphone.Megaphone"
api-version: 1.21

commands:
  megaphone:
    permission: megaphone.command
    aliases: [ "mp" ]
    description: "Execute various Megaphone actions."
    usage: "/megaphone [subcommand] ..."